name: Set up Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      env:
        REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
      uses: actions/deploy-pages@v4
