name: Deploy Rummy Score Tracker App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.1'

    # - name: Install dependencies
    #   run: npm install

    - name: Yarn Build
      run: yarn build

    - name: Build and Deploy
      env:
        REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
      run: npm run deploy
