name: Set up Environment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout code
      uses: actions/jekyll-build-pages@v1

    - name: Checkout code
      uses: actions/upload-pages-artifact@v3

    - name: Checkout code
      uses: actions/upload-artifact@v4

    - name: Build and Deploy
      env:
        REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
      uses: actions/deploy-pages@v4
